version: '3.8'

services:
  aics-api:
    image: ${DOCKER_USERNAME}/aics-api:latest
    container_name: aics-api
    ports:
      - "${AICS_API_PORT}:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
      - aics-network

  aics-admin:
    image: ${DOCKER_USERNAME}/aics-admin:latest
    container_name: aics-admin
    ports:
      - "${AICS_ADMIN_PORT}:8081"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
      - aics-network

  aics-auth:
    image: ${DOCKER_USERNAME}/aics-auth:latest
    container_name: aics-auth
    ports:
      - "${AICS_AUTH_PORT}:8082"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - postgres
      - redis
    networks:
      - aics-network

  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    volumes:
      - postgres-data:${DB_VOLUME_PATH}
    networks:
      - aics-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    networks:
      - aics-network

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - aics-network

networks:
  aics-network:
    driver: bridge

volumes:
  postgres-data:
  caddy_data:
  caddy_config: