services:
  aics-api:
    image: aics-api:latest
    container_name: aics-api
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_ISSUER: kgudevelopers@gmail.com
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FILE_SECRET_KEY: ${FILE_SECRET_KEY}
    networks:
      - aics-network

  aics-admin:
    image: aics-admin:latest
    container_name: aics-admin
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_ISSUER: kgudevelopers@gmail.com
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FILE_SECRET_KEY: ${FILE_SECRET_KEY}
    networks:
      - aics-network

  aics-auth:
    image: aics-auth:latest
    container_name: aics-auth
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_ISSUER: kgudevelopers@gmail.com
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      FILE_SECRET_KEY: ${FILE_SECRET_KEY}
    networks:
      - aics-network