apply plugin: 'jacoco'

jacoco {
    toolVersion = "0.8.11"
    reportsDirectory = layout.buildDirectory.dir('jacoco')
}

test {
    useJUnitPlatform()
    dependsOn testFixturesClasses

    // TestFixtures 소스를 포함
    testClassesDirs += sourceSets.testFixtures.output.classesDirs
    classpath += sourceSets.testFixtures.runtimeClasspath

    finalizedBy 'jacocoTestReport'
}

jacocoTestReport {
    dependsOn test
    executionData fileTree(dir: layout.buildDirectory, includes: ["jacoco/test.exec", "jacoco/testFixtures.exec"])
    reports {
        xml.required = true
        csv.required = false
        html.required = true
    }
    afterEvaluate {
        classDirectories.setFrom(files(classDirectories.files.collect {
            fileTree(dir: it, exclude: [
                    '**/request/**',
                    '**/response/**',
                    '**/exception/**',
                    '**/config/**',
                    '**/infrastructure/**',
                    '**/aspect/**',
                    '**/Q**',
                    'kgu/developers/api/AicsApiApplication.class',
                    // 현재는 미구현으로 인한 제외
                    '**/api/**/presentation/**',
                    '**/api/file/application/**'
            ])
        }))
    }

    finalizedBy 'jacocoTestCoverageVerification'
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport
    violationRules {
        rule {
            element = 'CLASS'

//            limit {
//                counter = 'LINE'
//                value = 'COVEREDRATIO'
//                minimum = 0.80
//            }
//
//            limit {
//                counter = 'BRANCH'
//                value = 'COVEREDRATIO'
//                minimum = 0.60
//            }

            excludes = [
                    '**/request/**',
                    '**/response/**',
                    '**/exception/**',
                    '**/config/**',
                    '**/infrastructure/**',
                    '**/aspect/**',
                    '**/Q**',
                    'kgu/developers/api/AicsApiApplication.class',
                    // 현재는 미구현으로 인한 제외
                    '**/api/**/presentation/**',
                    '**/api/file/application/**'
            ]
        }
    }
}

//task jacocoTestFixturesReport(type: JacocoReport) {
//    dependsOn testFixturesClasses
//    executionData fileTree(dir: layout.buildDirectory, includes: ["jacoco/testFixtures.exec"])
//    sourceDirectories.setFrom(files("src/testFixtures/java"))
//    classDirectories.setFrom(files("build/classes/java/testFixtures"))
//    reports {
//        xml.required = true
//        html.required = true
//    }
//}
