spring:
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

profiles:
  current-ip: ${CURRENT_IP}
  api-port: ${API_SERVER_PORT:8080}
  admin-api-port: ${ADMIN_API_SERVER_PORT:8081}
  auth-api-port: ${AUTH_API_SERVER_PORT:8082}