package mock;

import kgu.developers.common.response.PageableResponse;
import kgu.developers.common.response.PaginatedListResponse;
import kgu.developers.domain.post.domain.Category;
import kgu.developers.domain.post.domain.Post;
import kgu.developers.domain.post.domain.PostRepository;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakePostRepository implements PostRepository {
	private final List<Post> data = Collections.synchronizedList(new ArrayList<>());
	private final AtomicLong autoGeneratedId = new AtomicLong(0);

	@Override
	public Post save(Post post) {
		Post newPost = Post.builder()
			.id(autoGeneratedId.incrementAndGet())
			.title(post.getTitle())
			.content(post.getContent())
			.views(post.getViews())
			.category(post.getCategory())
			.author(post.getAuthor())
			.isPinned(post.isPinned())
			.comments(new ArrayList<>(post.getComments()))
			.file(post.getFile())
			.build();
		data.add(newPost);
		return newPost;
	}

	@Override
	public PaginatedListResponse<Post> findAllByTitleContainingAndCategoryOrderByCreatedAtDesc(
		String keyword, Category category, Pageable pageable
	) {
		List<Post> filteredPosts = data.stream()
			.filter(
				post -> post.getTitle().contains(keyword) && post.getCategory().equals(category)
			)
			.sorted(Comparator.comparing(Post::getCreatedAt).reversed())
			.collect(Collectors.toList());

		int start = (int) pageable.getOffset();
		int end = Math.min(start + pageable.getPageSize(), filteredPosts.size());

		List<Post> paginatedPosts = start > filteredPosts.size() ?
			Collections.emptyList() :
			filteredPosts.subList(start, end);

		List<Long> ids = paginatedPosts.stream()
			.map(Post::getId)
			.toList();

		return PaginatedListResponse.of(paginatedPosts, PageableResponse.of(pageable, ids));
	}

	@Override
	public Optional<Post> findById(Long postId) {
		return data.stream()
			.filter(post -> post.getId().equals(postId))
			.findAny();
	}

	@Override
	public void deleteAllByDeletedAtBefore(int retentionDays) {
		LocalDateTime threshold = LocalDateTime.now().minusDays(retentionDays);
		data.removeIf(post -> post.getDeletedAt() != null && post.getDeletedAt().isBefore(threshold));
	}
}
