package mock.repository;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

import org.springframework.data.domain.Pageable;

import kgu.developers.common.response.PageableResponse;
import kgu.developers.common.response.PaginatedListResponse;
import kgu.developers.domain.post.domain.Category;
import kgu.developers.domain.post.domain.Post;
import kgu.developers.domain.post.domain.PostRepository;

public class FakePostRepository implements PostRepository {
	private final List<Post> data = Collections.synchronizedList(new ArrayList<>());
	private final AtomicLong autoGeneratedId = new AtomicLong(0);

	@Override
	public Post save(Post post) {
		if (post == null) {
			throw new IllegalArgumentException("게시글은 null일 수 없습니다.");
		}
		if (post.getTitle() == null || post.getContent() == null) {
			throw new IllegalArgumentException("제목과 내용은 필수 입력값입니다.");
		}

		Post savedPost = Post.builder()
			.id(post.getId() == null ? autoGeneratedId.incrementAndGet() : post.getId())
			.title(post.getTitle())
			.content(post.getContent())
			.views(post.getViews())
			.category(post.getCategory())
			.authorId(post.getAuthorId())
			.isPinned(post.isPinned())
			.fileId(post.getFileId())
			.createdAt(getExistingCreatedAt(post.getId()))
			.updatedAt(LocalDateTime.now())
			.deletedAt(post.getDeletedAt())
			.build();

		if (post.getId() != null) {
			data.removeIf(p -> p.getId().equals(post.getId()));
		}

		data.add(savedPost);
		return savedPost;
	}

	private LocalDateTime getExistingCreatedAt(Long id) {
		return data.stream()
			.filter(p -> p.getId().equals(id))
			.findFirst()
			.map(Post::getCreatedAt)
			.orElse(LocalDateTime.now());
	}

	@Override
	public PaginatedListResponse<Post> findAllByTitleContainingAndCategoryOrderByCreatedAtDescIdDesc(
		List<String> keywords, Category category, Pageable pageable
	) {
		List<Post> filteredPosts = data.stream()
			.filter(
				post ->
					keywords.stream().anyMatch(keyword -> post.getTitle().contains(keyword))
					&& post.getCategory().equals(category)
					&& post.getDeletedAt() == null
			)
			.sorted(Comparator.comparing(Post::isPinned, Comparator.reverseOrder())
				.thenComparing(Post::getCreatedAt, Comparator.reverseOrder())
				.thenComparing(Post::getId, Comparator.reverseOrder()))
			.collect(Collectors.toList());

		int start = (int)pageable.getOffset();
		int end = Math.min(start + pageable.getPageSize(), filteredPosts.size());

		List<Post> paginatedPosts = start > filteredPosts.size() ?
			Collections.emptyList() :
			filteredPosts.subList(start, end);

		List<Long> ids = paginatedPosts.stream()
			.map(Post::getId)
			.toList();

		return PaginatedListResponse.of(paginatedPosts, PageableResponse.of(pageable, ids));
	}

	@Override
	public Optional<Post> findByIdAndDeletedAtIsNull(Long postId) {
		return data.stream()
			.filter(post -> post.getId().equals(postId)
				&& post.getDeletedAt() == null)
			.findAny();
	}

	@Override
	public void deleteAllByDeletedAtBefore(int retentionDays) {
		LocalDateTime threshold = LocalDateTime.now().minusDays(retentionDays);
		data.removeIf(post -> post.getDeletedAt() != null && post.getDeletedAt().isBefore(threshold));
	}

	@Override
	public Optional<Post> findByPrevPost(Long postId, LocalDateTime createdAt, Category category) {
		return data.stream()
			.filter(post -> isBeforePost(post, postId, createdAt) && post.getCategory().equals(category)
				&& post.getDeletedAt() == null)
			.max(Comparator.comparing(Post::getCreatedAt).thenComparing(Post::getId));
	}

	private boolean isBeforePost(Post post, Long postId, LocalDateTime createdAt) {
		return post.getCreatedAt().isBefore(createdAt)
			|| (post.getCreatedAt().equals(createdAt) && post.getId() < postId);
	}

	@Override
	public Optional<Post> findByNextPost(Long postId, LocalDateTime createdAt, Category category) {
		return data.stream()
			.filter(post -> isAfterPost(post, postId, createdAt) && post.getCategory().equals(category)
				&& post.getDeletedAt() == null)
			.min(Comparator.comparing(Post::getCreatedAt).thenComparing(Post::getId));
	}

	private boolean isAfterPost(Post post, Long postId, LocalDateTime createdAt) {
		return post.getCreatedAt().isAfter(createdAt)
			|| (post.getCreatedAt().equals(createdAt) && post.getId() > postId);
	}
}
