package mock.repository;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;

import kgu.developers.domain.lab.domain.Lab;
import kgu.developers.domain.lab.domain.LabRepository;

public class FakeLabRepository implements LabRepository {
	private final List<Lab> data = Collections.synchronizedList(new ArrayList<>());
	private final AtomicLong autoGeneratedId = new AtomicLong(0);

	@Override
	public Lab save(Lab lab) {
		if (lab == null) {
			throw new IllegalArgumentException("Lab은 null일 수 없습니다.");
		}
		if (lab.getName() == null
			|| lab.getLoc() == null
			|| lab.getSite() == null
			|| lab.getAdvisor() == null) {
			throw new IllegalArgumentException("이름, 위치, 사이트, 지도교수는 필수 입력값입니다.");
		}

		Lab newLab = Lab.builder()
			.id(autoGeneratedId.incrementAndGet())
			.name(lab.getName())
			.loc(lab.getLoc())
			.site(lab.getSite())
			.advisor(lab.getAdvisor())
			.build();

		data.add(newLab);
		return newLab;
	}

	@Override
	public Optional<Lab> findById(Long id) {
		return data.stream()
			.filter(lab -> lab.getId().equals(id))
			.findFirst();
	}

	@Override
	public List<Lab> findAllByOrderByName() {
		return data.stream()
			.sorted(Comparator.comparing(Lab::getName))
			.toList();
	}

	@Override
	public void deleteById(Long id) {
		data.removeIf(lab -> lab.getId().equals(id));
	}
}
