package mock.repository;

import kgu.developers.common.response.PageableResponse;
import kgu.developers.common.response.PaginatedListResponse;
import kgu.developers.domain.graduationUser.domain.GraduationType;
import kgu.developers.domain.graduationUser.domain.GraduationUser;
import kgu.developers.domain.graduationUser.domain.GraduationUserRepository;
import org.springframework.data.domain.Pageable;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeGraduationUserRepository implements GraduationUserRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<GraduationUser> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public GraduationUser save(GraduationUser graduationUser) {
        GraduationUser newGraduationUser = GraduationUser.builder()
            .id(graduationUser.getId() == null ? autoGeneratedId.getAndIncrement() : graduationUser.getId())
            .name(graduationUser.getName())
            .email(graduationUser.getEmail())
            .advisorProfessor(graduationUser.getAdvisorProfessor())
            .graduationType(graduationUser.getGraduationType())
            .graduationDate(graduationUser.getGraduationDate())
            .capstoneCompletion(graduationUser.getCapstoneCompletion())
            .department(graduationUser.getDepartment())
            .midThesisId(graduationUser.getMidThesisId())
            .finalThesisId(graduationUser.getFinalThesisId())
            .certificateId(graduationUser.getCertificateId())
            .userId(graduationUser.getUserId())
            .createdAt(graduationUser.getCreatedAt())
            .deletedAt(graduationUser.getDeletedAt())
            .updatedAt(graduationUser.getUpdatedAt())
            .build();

        data.add(newGraduationUser);

        return newGraduationUser;
    }

    @Override
    public Optional<GraduationUser> findByIdAndDeletedAtIsNull(Long graduationUserId) {
        return data.stream()
            .filter(user -> user.getId().equals(graduationUserId))
            .filter(user -> user.getDeletedAt() == null)
            .findFirst();
    }

    @Override
    public PaginatedListResponse<GraduationUser> findAllByNameAndGraduationTypeOrderByIdAsc(
        Pageable pageable, String name, GraduationType graduationType) {

        List<GraduationUser> sortedUsers = data.stream()
            .filter(user -> user.getDeletedAt() == null)
            .filter(user -> name == null || user.getName().contains(name))
            .filter(user -> graduationType == null || user.getGraduationType().equals(graduationType))
            .sorted(Comparator.comparing(GraduationUser::getId))
            .collect(Collectors.toList());

        int start = (int) pageable.getOffset();
        int end = Math.min((start + pageable.getPageSize()), sortedUsers.size());

        List<GraduationUser> paginatedUsers = start > sortedUsers.size()
            ? Collections.emptyList()
            : sortedUsers.subList(start, end);

        List<Long> graduationUserIds = sortedUsers.stream()
            .map(GraduationUser::getId)
            .collect(Collectors.toList());

        return PaginatedListResponse.of(
            paginatedUsers,
            PageableResponse.of(pageable, graduationUserIds)
        );
    }

    @Override
    public List<GraduationUser> findAllByGraduationTypeOrderByIdAsc(GraduationType graduationType) {
        return data.stream()
            .filter(user -> user.getDeletedAt() == null)
            .filter(user -> graduationType == null || user.getGraduationType().equals(graduationType))
            .sorted(Comparator.comparing(GraduationUser::getId))
            .toList();
    }

    @Override
    public Optional<GraduationUser> findByUserIdAndDeletedAtIsNull(String id) {
        return data.stream()
            .filter(user -> user.getUserId().equals(id))
            .filter(user -> user.getDeletedAt() == null)
            .findFirst();
    }
}
