package mock.repository;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.stream.Collectors;

import org.springframework.data.domain.Pageable;

import kgu.developers.common.response.PageableResponse;
import kgu.developers.common.response.PaginatedListResponse;
import kgu.developers.domain.user.domain.User;
import kgu.developers.domain.user.domain.UserRepository;

public class FakeUserRepository implements UserRepository {

	// private final AtomicLong autoGeneratedId = new AtomicLong(0);
	private final List<User> data = Collections.synchronizedList(new ArrayList<>());

	@Override
	public User save(User user) {
		User newUser = User.builder()
			.id(user.getId())
			.password(user.getPassword())
			.name(user.getName())
			.email(user.getEmail())
			.phone(user.getPhone())
			.role(user.getRole())
			.major(user.getMajor())
			.build();
		data.add(newUser);
		return newUser;
	}

	@Override
	public boolean existsById(String userId) {
		return data.stream().anyMatch(item -> item.getId().equals(userId));
	}

	@Override
	public Optional<User> findById(String userId) {
		return data.stream().filter(item -> item.getId().equals(userId)).findAny();
	}

	@Override
	public PaginatedListResponse findAllByNameOrderByIdDesc(Pageable pageable, String name) {
		List<User> sortedUsers = data.stream()
			.filter(user -> name == null || user.getName().contains(name))
			.sorted(Comparator.comparing(User::getId).reversed())
			.collect(Collectors.toList());

		int start = (int)pageable.getOffset();
		int end = Math.min((start + pageable.getPageSize()), sortedUsers.size());

		List<User> paginatedUsers = start > sortedUsers.size() ?
			Collections.emptyList() :
			sortedUsers.subList(start, end);

		List<String> userIds = sortedUsers.stream()
			.map(User::getId)
			.collect(Collectors.toList());

		return PaginatedListResponse.of(paginatedUsers, PageableResponse.of(pageable, userIds));
	}

	@Override
	public void deleteAllByDeletedAtBefore(int retentionDays) {
		LocalDateTime threshold = LocalDateTime.now().minusDays(retentionDays);
		data.removeIf(user -> user.getDeletedAt() != null && user.getDeletedAt().isBefore(threshold));
	}

	@Override
	public List<User> findAllById(List<String> ids) {
		return data.stream().filter(item -> ids.contains(item.getId())).collect(Collectors.toList());
	}
}
