-- 테이블 생성
-- about
CREATE TABLE about
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at      TIMESTAMP(6)          DEFAULT NULL,
    content         TEXT         NOT NULL,
    description VARCHAR(100),
    category   VARCHAR(50)  NOT NULL UNIQUE
       CONSTRAINT about_category_check
           CHECK ((category)::TEXT = ANY (ARRAY ['DEPT_INTRO', 'DIRECTIONS', 'CLUB']))
);

-- club
CREATE TABLE club
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(16)  NOT NULL UNIQUE,
    description VARCHAR(100)  NOT NULL,
    site        VARCHAR(50)           DEFAULT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at  TIMESTAMP(6)          DEFAULT NULL
);

-- professor
CREATE TABLE professor
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(10)  NOT NULL,
    contact    VARCHAR(15)  NOT NULL UNIQUE,
    email      VARCHAR(50)  NOT NULL UNIQUE,
    img        VARCHAR(255) NOT NULL,
    office_loc VARCHAR(20)  NOT NULL,
    role       VARCHAR(20)  NOT NULL
        CONSTRAINT professor_role_check
            CHECK ((role)::TEXT = ANY (ARRAY ['PROFESSOR', 'ASSISTANT'])),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)          DEFAULT NULL
);

-- file_entity
CREATE TABLE file_entity
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    logical_name  VARCHAR(100)  NOT NULL,
    physical_path VARCHAR(2083) NOT NULL UNIQUE,
    file_size     VARCHAR(10) NOT NULL,
    extension     VARCHAR(10) NOT NULL,
    created_at    TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at    TIMESTAMP(6)           DEFAULT NULL
);

-- lab
CREATE TABLE lab
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(16)  NOT NULL,
    loc        VARCHAR(10)  NOT NULL,
    site       VARCHAR(50)  NOT NULL,
    advisor    VARCHAR(16)  NOT NULL,
    file_id    BIGINT UNIQUE,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)          DEFAULT NULL,
    CONSTRAINT fk_lab_file FOREIGN KEY (file_id) REFERENCES file_entity (id)
        ON DELETE SET NULL
);

-- carousel
CREATE TABLE carousel
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id    BIGINT        NOT NULL UNIQUE,
    text       VARCHAR(500)  NOT NULL,
    link       VARCHAR(2083) NOT NULL,
    created_at TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)           DEFAULT NULL,
    CONSTRAINT fk_carousel_file FOREIGN KEY (file_id) REFERENCES file_entity (id)
        ON DELETE SET NULL
);

-- user
CREATE TABLE "user"
(
    id         VARCHAR(10)  NOT NULL PRIMARY KEY,
    name       VARCHAR(10)  NOT NULL,
    phone      VARCHAR(15)  NOT NULL UNIQUE,
    email      VARCHAR(50)  NOT NULL UNIQUE,
    major      VARCHAR(50)  NOT NULL
        CONSTRAINT user_major_check
            CHECK ((major)::TEXT = ANY (ARRAY ['CSE', 'AIT', 'SSS'])),
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL
        CONSTRAINT user_role_check
            CHECK ((role)::TEXT = ANY (ARRAY ['USER', 'ADMIN', 'SUPER'])),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)          DEFAULT NULL
);

-- post
CREATE TABLE post
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title      VARCHAR(100) NOT NULL,
    content    TEXT         NOT NULL,
    views      INTEGER      NOT NULL DEFAULT 0,
    is_pinned  BOOLEAN      NOT NULL DEFAULT FALSE,
    category   VARCHAR(50)
        CONSTRAINT post_category_check
            CHECK ((category)::TEXT = ANY
                   (ARRAY ['NOTIFICATION', 'NEWS'])),
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)          DEFAULT NULL,
    file_id    BIGINT UNIQUE,
    author_id  VARCHAR(10),
    CONSTRAINT fk_post_file FOREIGN KEY (file_id) REFERENCES file_entity (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES "user" (id)
        ON DELETE SET NULL ON UPDATE CASCADE
);

-- comment
CREATE TABLE comment
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content    VARCHAR(500) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMP(6)          DEFAULT NULL,
    post_id    BIGINT       NOT NULL,
    author_id  VARCHAR(10)  NOT NULL,
    CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES post (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES "user" (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
