-- Enum 타입 정의
-- about
CREATE TYPE main_category_type AS ENUM ('DEPT_INTRO', 'EDU_ACTIVITIES');
CREATE TYPE sub_category_type AS ENUM ('DEPT_INTRO', 'HISTORY', 'EDU_ENVIRONMENT', 'EDU_OBJECTIVES', 'CURRICULUM', 'LEARNING_ACTIVITIES', 'CLUB_INTRO');

--post
CREATE TYPE post_category AS ENUM ('DEPT_INFO', 'LESSON_INFO', 'EMPLOY_INFO', 'DEPT_NEWS', 'GOOD_WORKS', 'AWARDED');

--professor
CREATE TYPE professor_role AS ENUM ('PROFESSOR', 'ASSISTANT');

-- user
CREATE TYPE user_role AS ENUM ('USER', 'ADMIN', 'SUPER');
CREATE TYPE user_major AS ENUM ('CSE', 'AIT', 'SSS');


-- 테이블 생성
-- about
CREATE TABLE about (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       created_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at      TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       deleted_at      TIMESTAMP(6) DEFAULT NULL,
                       content         TEXT NOT NULL,
                       detail_category VARCHAR(100),
                       main_category   main_category_type NOT NULL,
                       sub_category    sub_category_type NOT NULL
);

-- lab
CREATE TABLE lab (
                     id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name        VARCHAR(16) NOT NULL,
                     loc         VARCHAR(10) NOT NULL,
                     site        VARCHAR(50) NOT NULL,
                     created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                     deleted_at  TIMESTAMP(6) DEFAULT NULL
);

-- professor
CREATE TABLE professor (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name        VARCHAR(10) NOT NULL,
                           contact     VARCHAR(15) NOT NULL UNIQUE,
                           email       VARCHAR(50) NOT NULL UNIQUE,
                           role        professor_role NOT NULL,
                           created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           deleted_at  TIMESTAMP(6) DEFAULT NULL
);

-- file_entity
CREATE TABLE file_entity (
                             id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             logical_name  VARCHAR(100) NOT NULL,
                             physical_path VARCHAR(2083) NOT NULL UNIQUE,
                             created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             updated_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             deleted_at    TIMESTAMP(6) DEFAULT NULL
);

-- carousel
CREATE TABLE carousel (
                          id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          file_id     BIGINT NOT NULL UNIQUE,
                          text        VARCHAR(500) NOT NULL,
                          link        VARCHAR(2083) NOT NULL,
                          created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          deleted_at  TIMESTAMP(6) DEFAULT NULL,
                          CONSTRAINT fk_carousel_file FOREIGN KEY (file_id) REFERENCES file_entity (id)
);

-- user
CREATE TABLE "user" (
                        id          VARCHAR(10) NOT NULL PRIMARY KEY,
                        name        VARCHAR(10) NOT NULL,
                        phone       VARCHAR(15) NOT NULL UNIQUE,
                        email       VARCHAR(50) NOT NULL UNIQUE,
                        major       user_major NOT NULL,
                        password    VARCHAR(255) NOT NULL,
                        role        user_role NOT NULL,
                        created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                        deleted_at  TIMESTAMP(6) DEFAULT NULL
);

-- post
CREATE TABLE post (
                      id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      title       VARCHAR(100) NOT NULL,
                      content     TEXT NOT NULL,
                      views       INTEGER NOT NULL DEFAULT 0,
                      is_pinned   BOOLEAN NOT NULL DEFAULT FALSE,
                      category    post_category,
                      created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      deleted_at  TIMESTAMP(6) DEFAULT NULL,
                      file_id     BIGINT UNIQUE,
                      author_id   VARCHAR(10),
                      CONSTRAINT fk_post_file FOREIGN KEY (file_id) REFERENCES file_entity (id),
                      CONSTRAINT fk_post_author FOREIGN KEY (author_id) REFERENCES "user" (id)
);

-- comment
CREATE TABLE comment (
                         id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         content     VARCHAR(500) NOT NULL,
                         created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         updated_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
                         deleted_at  TIMESTAMP(6) DEFAULT NULL,
                         post_id     BIGINT NOT NULL,
                         author_id   VARCHAR(10) NOT NULL,
                         CONSTRAINT fk_comment_post FOREIGN KEY (post_id) REFERENCES post (id) ON DELETE CASCADE,
                         CONSTRAINT fk_comment_author FOREIGN KEY (author_id) REFERENCES "user" (id) ON DELETE CASCADE
);


-- 인덱스 추가
-- about
CREATE INDEX idx_about_main_category ON about(main_category);
CREATE INDEX idx_about_sub_category ON about(sub_category);

-- carousel
CREATE INDEX idx_carousel_file_id ON carousel (file_id);


-- comment
CREATE INDEX idx_comment_post_id ON comment (post_id);
CREATE INDEX idx_comment_author_id ON comment (author_id);

-- lab
CREATE INDEX idx_lab_name ON lab (name);
CREATE INDEX idx_lab_site ON lab (site);

-- post
CREATE INDEX idx_post_title ON post (title);
CREATE INDEX idx_post_category ON post (category);
CREATE INDEX idx_post_author_id ON post (author_id);